name: image

on:
  push:
    tags:
      - v*.*.*
    branches:
      - 'main'

env:
  IMAGE_NAME: markdown-to-pdf-py

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
      statuses: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Test build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:test_build
          load: true

      - name: Scan Image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:test_build"
          fail-build: false
          # severity-cutoff: critical

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Determine tag
        id: tag
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Final build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag}}"

      - name: Create SBoM
        uses: anchore/sbom-action@v0
        id: sbom
        with:
          image: "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag}}"